# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocorrencia',
            name='raca',
        ),
        migrations.DeleteModel(
            name='Raca',
        ),
    ]
