# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0002_auto_20160407_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocorrencia',
            name='doenca',
        ),
        migrations.RemoveField(
            model_name='ocorrencia',
            name='endereco',
        ),
        migrations.DeleteModel(
            name='Doenca',
        ),
        migrations.DeleteModel(
            name='Ocorrencia',
        ),
    ]
