# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0003_auto_20160407_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='logradouro',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='rua',
        ),
        migrations.AddField(
            model_name='endereco',
            name='endereco_completo',
            field=models.CharField(default='', max_length=200),
        ),
    ]
