# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0005_doencas_faixaetaria_raca_sexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('doenca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webservices.Doencas')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webservices.Endereco')),
                ('faixa_etaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webservices.FaixaEtaria')),
                ('raca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webservices.Raca')),
                ('sexo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webservices.Sexo')),
            ],
        ),
    ]
