# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0006_ocorrencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='longitude',
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
    ]
