# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0007_auto_20160505_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faixaetaria',
            name='nome',
            field=models.CharField(choices=[('Filhote', 'Filhote'), ('Jovem', 'Jovem'), ('Adulto', 'Adulto'), ('Idoso', 'Idoso')], max_length=8),
        ),
    ]
