# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0008_auto_20160505_1958'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doencas',
            new_name='Doenca',
        ),
        migrations.AlterField(
            model_name='faixaetaria',
            name='nome',
            field=models.CharField(default='', max_length=8),
        ),
    ]
