# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 22:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0009_auto_20160506_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocorrencia',
            name='endereco',
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='bairro',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='cidade',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='endereco_completo',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='estado',
            field=models.CharField(default='MS', max_length=2),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data',
            field=models.DateField(default=datetime.datetime(2016, 5, 7, 22, 13, 2, 283884, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Endereco',
        ),
    ]
