# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 22:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0010_auto_20160507_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 7, 22, 20, 9, 232758)),
        ),
    ]
