# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 22:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0012_auto_20160507_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
