# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-21 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0013_auto_20160507_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='teste',
            field=models.CharField(default='banana', max_length=8),
        ),
    ]
