# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-21 18:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0014_ocorrencia_teste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocorrencia',
            name='teste',
        ),
    ]
