# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-10 03:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webservices', '0015_remove_ocorrencia_teste'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=100)),
                ('estado', models.CharField(default='MS', max_length=2)),
                ('tipo_inscricao', models.CharField(default='Primária', max_length=10)),
                ('situacao', models.CharField(default='Atuante', max_length=10)),
                ('crmv', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='veterinario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='webservices.Veterinario'),
            preserve_default=False,
        ),
    ]
